In [3]:
#PANDAS Data Frames
import pandas as pd

#to generate random numbers
from numpy.random import randn

In [4]:
#2dimensional data structures - list
print("Some two-dimensional data types:")
list_2dim = [[10112,"Berlin",3460725],[20095,"Hamburg",1786445],[80331,"München",1353185]]
print("\nThis is a simple 2dim list:")
print (list_2dim)
print(type(list_2dim))

print(list_2dim[1][2])

Some two-dimensional data types:

This is a simple 2dim list:
[[10112, 'Berlin', 3460725], [20095, 'Hamburg', 1786445], [80331, 'München', 1353185]]
<class 'list'>
1786445


In [5]:
#2dimensional data structures - array
array_ran = randn(3,3)
print("\nThis is a simple 2dim array:")
print (array_ran)
print(type(array_ran))

print (array_ran[0,1])


This is a simple 2dim array:
[[-0.73555851 -0.89658479  1.48148392]
 [ 0.7476548  -0.57906925  0.02173616]
 [ 0.84948776 -0.01705421  0.24930153]]
<class 'numpy.ndarray'>
-0.8965847867558402


In [6]:
#2dimensional data structures - PANDAS data frame
df = pd.DataFrame(randn(3,3),index=['ID1','ID2','ID3'],columns=['A1','A2','A3'])
print(type(df))
print("\nThis is a PANDAS dataframe:")
df

<class 'pandas.core.frame.DataFrame'>

This is a PANDAS dataframe:


A1        A2        A3
ID1  1.156480 -1.141239 -0.480097
ID2 -0.337587 -0.924076  0.404744
ID3 -1.365335 -2.102394  0.083764

In [7]:
#select column
df['A1']

ID1    1.156480
ID2   -0.337587
ID3   -1.365335
Name: A1, dtype: float64

In [8]:
#select list of columns 
df[['A1','A3']]

A1        A3
ID1  1.156480 -0.480097
ID2 -0.337587  0.404744
ID3 -1.365335  0.083764

In [9]:
#create new column
df['A1+A2']=df['A1']+df['A2']
df

A1        A2        A3     A1+A2
ID1  1.156480 -1.141239 -0.480097  0.015241
ID2 -0.337587 -0.924076  0.404744 -1.261662
ID3 -1.365335 -2.102394  0.083764 -3.467729

In [14]:
#drop column temporarily
df.drop('A1+A2', axis=1)

A1        A2        A3
ID1  1.156480 -1.141239 -0.480097
ID2 -0.337587 -0.924076  0.404744
ID3 -1.365335 -2.102394  0.083764

In [ ]:
df

A1        A2        A3     A1+A2
ID1 -1.097623 -0.221931  0.061108 -1.319554
ID2  2.080732  0.588560  0.535315  2.669292
ID3 -1.349365  0.712107  0.475281 -0.637258

In [ ]:
#drop column permanently
df.drop('A1+A2',axis=1,inplace=True)

In [ ]:
df

A1        A2        A3
ID1 -1.097623 -0.221931  0.061108
ID2  2.080732  0.588560  0.535315
ID3 -1.349365  0.712107  0.475281

In [ ]:
#select row
df.loc['ID1']

A1   -1.097623
A2   -0.221931
A3    0.061108
Name: ID1, dtype: float64

In [ ]:
#drop row temp
df.drop('ID1',axis=0)

A1        A2        A3
ID2  2.080732  0.588560  0.535315
ID3 -1.349365  0.712107  0.475281

In [ ]:
#select rows and columns at once
df.loc[['ID2','ID3'],['A1','A2']]

A1        A2
ID2  2.080732  0.588560
ID3 -1.349365  0.712107

In [ ]:
df

A1        A2        A3
ID1 -1.097623 -0.221931  0.061108
ID2  2.080732  0.588560  0.535315
ID3 -1.349365  0.712107  0.475281

In [ ]:
#conditional selection
df >= 0

A1     A2    A3
ID1  False  False  True
ID2   True   True  True
ID3  False   True  True

In [ ]:
#conditional selection
df[df['A3']>=0]
#df[df['A3']<0]['A1']

A1        A2        A3
ID1 -1.097623 -0.221931  0.061108
ID2  2.080732  0.588560  0.535315
ID3 -1.349365  0.712107  0.475281

In [ ]:
#descriptive statistics
df.describe()

A1        A2        A3
count  3.000000  3.000000  3.000000
mean  -0.122085  0.359578  0.357235
std    1.911844  0.507376  0.258204
min   -1.349365 -0.221931  0.061108
25%   -1.223494  0.183314  0.268195
50%   -1.097623  0.588560  0.475281
75%    0.491555  0.650333  0.505298
max    2.080732  0.712107  0.535315

In [ ]:
#non-missing values and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, ID1 to ID3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A1      3 non-null      float64
 1   A2      3 non-null      float64
 2   A3      3 non-null      float64
dtypes: float64(3)
memory usage: 176.0+ bytes
